{{- if .Values.frontend.pdb.create }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "townsquare.frontend.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if .Values.frontend.pdb.minAvailable }}
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.frontend.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.frontend.pdb.maxUnavailable }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.frontend.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
