apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "townsquare.backend.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  USE_TLS: {{ .Values.backend.server.useTls | quote }}
  SERVER_PORT: {{ .Values.backend.server.port | quote }}
  {{- if .Values.backend.server.allowedOrigins }}
  ALLOWED_ORIGINS: {{ .Values.backend.server.allowedOrigins | quote }}
  {{- end }}
  {{- if .Values.backend.server.useTls }}
  CERT_FILE: {{ .Values.backend.server.certFile | quote }}
  KEY_FILE: {{ .Values.backend.server.keyFile | quote }}
  {{- end }}
